services:
  - type: web
    name: backend-ccc
    env: docker
    region: oregon
    plan: starter
    branch: main
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: postgres-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: postgres-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: postgres-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: postgres-db
          property: database
      - key: JWT_SECRET
        sync: false
      - key: SHOPIFY_SHOP_NAME
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: SHOPIFY_STOREFRONT_TOKEN
        sync: false
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_WEBHOOK_SECRET
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false

databases:
  - name: postgres-db
    region: oregon
    plan: starter 